# test
name: version, tag and github release

on:
  push:
    branches: [master]

jobs:
  release:
    uses: salesforcecli/github-workflows/.github/workflows/githubRelease.yml@main
    secrets: inherit

  # most repos won't use this
  # depends on previous job to avoid git collisions, not for any functionality reason
  # docs:
  #   uses: salesforcecli/github-workflows/.github/workflows/publishTypedoc.yml@main
  #   secrets: inherit
  #   needs: release
